"""Read-only access to the public Deadlock API.

Two things live here because both the identity backfill and the match importer need them:
fetching a match's per-player rows, and translating the API's hero ids and names into ours.

The API needs no auth and has no documented rate limit on the metadata endpoint. It does
refuse Python's default User-Agent with a 403, which is easy to misread as the API being down,
so every request here carries a real one.

A match the API never ingested - every custom lobby, which is 34 of our 82 - returns a non-200
rather than an empty result. That is not an error condition to retry: those matches are not in
the database and never will be, so a miss is a fact worth caching like any other.
"""
import json
import os
from concurrent.futures import ThreadPoolExecutor

import requests

from utils import data_io, dates

METADATA_URL = "https://api.deadlock-api.com/v1/matches/{}/metadata"
HEROES_URL = "https://assets.deadlock-api.com/v2/heroes"
HEADERS = {"User-Agent": "deadlock-stats-app/1.0 (PUG stats)"}
TIMEOUT = 25
WORKERS = 4

# The per-player fields we keep. The metadata payload is large - item builds, ability upgrades,
# per-death detail - and none of the rest is used for identity or for the match importer.
PLAYER_FIELDS = ("account_id", "kills", "deaths", "assists", "net_worth",
                 "hero_id", "team", "player_slot", "mvp_rank")

# Where our hero names differ from the API's. Everything else matches exactly; this is the
# whole list, generated by diffing data/heroes.json against the assets endpoint.
HERO_ALIASES = {
    "Mo and Krill": "Mo & Krill",
    "Doorman": "The Doorman",
}

_hero_names = None


def hero_names():
    """{hero_id: API hero name}, fetched once per process."""
    global _hero_names
    if _hero_names is None:
        r = requests.get(HEROES_URL, headers=HEADERS, timeout=TIMEOUT)
        r.raise_for_status()
        _hero_names = {h["id"]: h["name"] for h in r.json()}
    return _hero_names


def our_hero_name_matches(ours, hero_id):
    """True when our hero name and the API's hero_id are the same hero."""
    return HERO_ALIASES.get(ours, ours) == hero_names().get(hero_id)


def match_info(match_id):
    """The full `match_info` payload for a match, or None when the API does not have it."""
    try:
        r = requests.get(METADATA_URL.format(match_id), headers=HEADERS, timeout=TIMEOUT)
        if r.status_code != 200:
            return None
        return r.json().get("match_info") or None
    except (requests.RequestException, ValueError):
        return None


def match_players(match_id):
    """The 12 per-player rows for a match, or None when the API does not have it."""
    players = (match_info(match_id) or {}).get("players", [])
    rows = [{k: p.get(k) for k in PLAYER_FIELDS} for p in players]
    return rows or None


# ---------------------------------------------------------------- the match importer

# The API numbers the sides; we name them. Checked against every match we had logged by hand.
TEAM_NAMES = {0: "Hidden King", 1: "Archmother"}


def our_hero_name(hero_id, heroes):
    """Our name for an API hero id, or None for a hero we have not added - a new release.

    Read from the vendored hero_visuals.json rather than the assets endpoint, which lives on a
    different host: importing a match should not fail because the portrait server is down.
    """
    by_id = {v.get("id"): name for name, v in data_io.load_hero_visuals().items()}
    name = by_id.get(hero_id)
    return name if name in heroes else None


def _k(value):
    return round((value or 0) / 1000, 1)


def to_match(info, players, heroes):
    """An API `match_info` payload as a match in our own shape, ready to fill the form.

    Each player row carries its `account_id`, and `player` is None where no record owns that
    account yet - the form leaves that slot for a person to fill, then links the account so the
    next import knows them. `hero` is likewise None for a hero we have not added.

    Every column maps onto what the post-game scoreboard shows, which is what we used to type:
    souls are `net_worth`, objective damage is `boss_damage`, and "Healing" is healing *plus*
    barrier - `player_healing` alone came in low for exactly the heroes that shield. Measured
    against the hand-entered rows it reproduces, see tests/test_import.py.
    """
    winning_team = info.get("winning_team")
    rows = []
    for p in sorted(info.get("players", []), key=lambda p: (p.get("team"), p.get("player_slot") or 0)):
        final = (p.get("stats") or [{}])[-1]
        key = data_io.key_for_account(p["account_id"], players)
        rows.append({
            "team": TEAM_NAMES.get(p.get("team")),
            "account_id": str(p["account_id"]),
            "player": players[key].get("display_name", key) if key else None,
            "hero": our_hero_name(p.get("hero_id"), heroes),
            "hero_id": p.get("hero_id"),
            "win": p.get("team") == winning_team,
            "mvp": p.get("mvp_rank") == 1,
            "key_player": p.get("mvp_rank") in (2, 3),
            "kills": p.get("kills") or 0,
            "deaths": p.get("deaths") or 0,
            "assists": p.get("assists") or 0,
            "souls_k": _k(p.get("net_worth")),
            "plr_damage_k": _k(final.get("player_damage")),
            "obj_damage_k": _k(final.get("boss_damage")),
            "healing_k": _k((final.get("player_healing") or 0) + (final.get("player_barriering") or 0)),
        })

    minutes, seconds = divmod(int(info.get("duration_s") or 0), 60)
    start = info.get("start_time")
    return {
        "match_id": str(info.get("match_id")),
        "date": dates.local_date(start) if start else None,
        "game_length": f"{minutes}:{seconds:02d}",
        "players": rows,
    }


def match_players_cached(match_ids, cache_file):
    """{match_id: rows or None} for many matches, memoised on disk across runs.

    Misses are cached alongside hits, so a re-run does not spend a timeout per custom lobby
    rediscovering that the API still does not have it.
    """
    cache = {}
    if os.path.exists(cache_file):
        with open(cache_file, encoding="utf-8") as fh:
            cache = json.load(fh)

    todo = [m for m in match_ids if m not in cache]
    if todo:
        print(f"Fetching {len(todo)} match{'es' if len(todo) != 1 else ''} from the API...")
        with ThreadPoolExecutor(WORKERS) as pool:
            for match_id, rows in zip(todo, pool.map(match_players, todo)):
                cache[match_id] = rows
        with open(cache_file, "w", encoding="utf-8") as fh:
            json.dump(cache, fh, indent=1)

    return {m: cache.get(m) for m in match_ids}
