"""Read-only access to the public Deadlock API.

Two things live here because both the identity backfill and the match importer need them:
fetching a match's per-player rows, and translating the API's hero ids and names into ours.

The API needs no auth and has no documented rate limit on the metadata endpoint. It does
refuse Python's default User-Agent with a 403, which is easy to misread as the API being down,
so every request here carries a real one.

A match the API never ingested - every custom lobby, which is 34 of our 82 - returns a non-200
rather than an empty result. That is not an error condition to retry: those matches are not in
the database and never will be, so a miss is a fact worth caching like any other.
"""
import json
import os
from concurrent.futures import ThreadPoolExecutor

import requests

METADATA_URL = "https://api.deadlock-api.com/v1/matches/{}/metadata"
HEROES_URL = "https://assets.deadlock-api.com/v2/heroes"
HEADERS = {"User-Agent": "deadlock-stats-app/1.0 (PUG stats)"}
TIMEOUT = 25
WORKERS = 4

# The per-player fields we keep. The metadata payload is large - item builds, ability upgrades,
# per-death detail - and none of the rest is used for identity or for the match importer.
PLAYER_FIELDS = ("account_id", "kills", "deaths", "assists", "net_worth",
                 "hero_id", "team", "player_slot", "mvp_rank")

# Where our hero names differ from the API's. Everything else matches exactly; this is the
# whole list, generated by diffing data/heroes.json against the assets endpoint.
HERO_ALIASES = {
    "Mo and Krill": "Mo & Krill",
    "Doorman": "The Doorman",
}

_hero_names = None


def hero_names():
    """{hero_id: API hero name}, fetched once per process."""
    global _hero_names
    if _hero_names is None:
        r = requests.get(HEROES_URL, headers=HEADERS, timeout=TIMEOUT)
        r.raise_for_status()
        _hero_names = {h["id"]: h["name"] for h in r.json()}
    return _hero_names


def our_hero_name_matches(ours, hero_id):
    """True when our hero name and the API's hero_id are the same hero."""
    return HERO_ALIASES.get(ours, ours) == hero_names().get(hero_id)


def match_players(match_id):
    """The 12 per-player rows for a match, or None when the API does not have it."""
    try:
        r = requests.get(METADATA_URL.format(match_id), headers=HEADERS, timeout=TIMEOUT)
        if r.status_code != 200:
            return None
        players = r.json().get("match_info", {}).get("players", [])
        rows = [{k: p.get(k) for k in PLAYER_FIELDS} for p in players]
        return rows or None
    except (requests.RequestException, ValueError):
        return None


def match_players_cached(match_ids, cache_file):
    """{match_id: rows or None} for many matches, memoised on disk across runs.

    Misses are cached alongside hits, so a re-run does not spend a timeout per custom lobby
    rediscovering that the API still does not have it.
    """
    cache = {}
    if os.path.exists(cache_file):
        with open(cache_file, encoding="utf-8") as fh:
            cache = json.load(fh)

    todo = [m for m in match_ids if m not in cache]
    if todo:
        print(f"Fetching {len(todo)} match{'es' if len(todo) != 1 else ''} from the API...")
        with ThreadPoolExecutor(WORKERS) as pool:
            for match_id, rows in zip(todo, pool.map(match_players, todo)):
                cache[match_id] = rows
        with open(cache_file, "w", encoding="utf-8") as fh:
            json.dump(cache, fh, indent=1)

    return {m: cache.get(m) for m in match_ids}
